# Generated by Django 4.2.20 on 2026-06-21 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0010_alter_prestamo_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2026, 7, 21, 17, 48, 38, 33371, tzinfo=datetime.timezone.utc)),
        ),
    ]
