# Generated by Django 4.2.20 on 2026-03-23 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0009_alter_prestamo_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2026, 4, 22, 22, 54, 59, 724436, tzinfo=datetime.timezone.utc)),
        ),
    ]
